# Basic
rand_seed: 2024
dataset: Gowalla
epoch: 1000
trn_batch: 4096
tensorboard: 0
device: cuda

# Early-stop
tst_step: 5
patience: 10
criterion: [1, 1]

# Test
metrics: [recall, ndcg]
ks: [10, 20]
tst_batch: 2048

# Fixed Options
keep_rate: 1.0
embed_dim: 64
lr: 1.0e-3

# Hyperparameter
reg_weight: 1.0e-4
layer_num: 3
a: 1.0
b: 1.1
alpha: 0.1

# Dev
comment: jgcf-gowalla
summary: jgcf-gowalla
model: jgcf
loss: bpr