# Basic
rand_seed: 2024
dataset: gowalla
epoch: 1500
trn_batch: 4096
tensorboard: 1

# Early-stop
tst_step: 5
patience: 10
criterion: [1, 1]

# Test
metrics: [recall, ndcg]
ks: [10, 20]
tst_batch: 2048

# Tunable
reg_weight: 1.0e-4
lr: 1.0e-3

# Develop (General)
comment: lightgcn
summary: lightgcn
model: lightgcn
loss: bpr

# Develop (Specific)
embed_dim: 64
layer_num: 4
keep_rate: 1.0