# Basic
rand_seed: 2024
dataset: gowalla
epoch: 1000
trn_batch: 4048
tensorboard: 0

# Early-stop
tst_step: 5
patience: 10
criterion: [1, 1]

# Test
metrics: [recall, ndcg]
ks: [10, 20]
tst_batch: 2048

# Utils
comment: multivae
summary: multivae
model: multivae
loss: vaeloss

# MultiVAE
mlp_hidden_size: 600
latent_dimension: 128
dropout_prob: 0.5
anneal_cap: 0.2
total_anneal_steps: 200000

