# Basic
rand_seed: 2024
dataset: yelp2018
epoch: 1500
trn_batch: 2048
tensorboard: 1

# Early-stop
tst_step: 5
patience: 10
criterion: [1, 1]

# Test
metrics: [recall, ndcg]
ks: [10, 20, 50]
tst_batch: 1024

# Develop (General)
comment: simplex-reprod
summary: simplex
model: simplex
loss: ccl

# Develop (Specific)
embed_dim: 64
keep_rate: 1.0
lr: 1.0e-3

# Data
neg_num: 100

# Loss
margin: 0.8
neg_weight: 200
embed_reg: 1.0e-4

# Model
score: 'cosine'
aggregator: 'mean'
fusing_weight: 0.5
attention_dropout: 0.0
history_num: 100
dropout: 0