####### Basic #######
tensorboard: 1
rand_seed: 2024
dataset: yelp2018
#####################

####### Model #######
comment: simplex-amazon
summary: simplex-amazon
model: simplex
loss: ccl
#####################

####### Train #######
trn_batch: 512
epoch: 2000
embed_dim: 64
lr: 1.0e-3
dropout: 0.1
#####################

####### Eval ########
metrics: [recall, ndcg]
ks: [10, 20]
criterion: [1, 1]  # Early-Stop
tst_step: 5
patience: 10
tst_batch: 2048
#####################

##### Specific ######
# Data
negative_num: 1000

# Loss
margin: 0.4
neg_weight: 300
embed_reg: 1.0e-6

# Model
score: 'cosine'
aggregator: 'mean'
fusing_weight: 0.5
attention_dropout: 0.0
history_num: 10
#####################
