####### Basic #######
tensorboard: 1
rand_seed: 2024
dataset: amazon-book
#####################

####### Model #######
comment: ultragcn-amazon
summary: ultragcn-amazon
model: ultragcn
loss: layerskiploss
#####################

####### Train #######
trn_batch: 1024
epoch: 2000
embed_dim: 64
lr: 1.0e-3
#####################

####### Loss ########
# L = -(w1 + w2*\beta)) * log(sigmoid(e_u e_i)) - \sum_{N-} (w3 + w4*\beta) * log(sigmoid(e_u e_i'))
w1: 1.0e-8
w2: 1.0
w3: 1.0
w4: 1.0e-8
negative_num: 500
negative_weight: 500
gamma: 1.0e-4  # weight of l2 normalization
lambda_: 2.75 # weight of L_I
sampling_sift_pos: False 
# whether to sift the pos item when doing negative sampling
#####################

####### Eval ########
metrics: [recall, ndcg]
ks: [10, 20, 50]
criterion: [1, 1]  # Early-Stop
tst_step: 5
patience: 10
tst_batch: 2048
#####################
